baseURL: /
theme: hugo-serif-theme
languageCode: en-us
title: factor~data
module:
  hugoVersion:
    extended: yes
    min: 0.55.0
params:
  colors:
    black: '#2f2f41'
    grey: '#5C5A5A'
    primary: '#4671dc'
    white: '#ffffff'
    white_offset: '#f6f7ff'
  fonts:
    base: Source Sans Pro
    google_fonts: https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap
    heading: Playfair Display
  footer:
    copyright_text: Free Hugo theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>
  google_analytics_id: ''
  google_tag_manager_id: ''
  homepage:
    show_contact_box: yes
    show_services_button: yes
  logo:
    alt: factor_data_logo
    desktop: images/logo/logo_factor_color.png
    desktop_height: 72px
    mobile: images/logo/logo_factor_chico.png
    mobile_height: 36px
  seo:
    meta_og_image: https://www.zerostatic.io/theme/hugo-serif/hugo-serif-screenshot.png
    meta_twitter_creator: '@zerostaticio'
    meta_twitter_site: '@zerostaticio'
  projects:
    summary_truncate: 400
  team:
    summary_large_truncate: 400
menu:
  footer:
    - name: Inicio
      url: /
      weight: 1
    - name: Contacto
      url: /contact/
      weight: 2
  main:
    - name: Líneas de trabajo
      url: /lines/
      weight: 1
    - name: Equipo
      url: /team/
      weight: 2
    - name: Sobre nosotros
      url: /about/
      weight: 3
    - name: Publicaciones
      url: /publicaciones/
      weight: 4
    - name: Contacto
      url: /contact/
      weight: 5
